# Generated by Django 3.2.9 on 2021-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='location',
        ),
        migrations.RemoveField(
            model_name='items',
            name='name',
        ),
        migrations.AddField(
            model_name='items',
            name='aisle_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='allergy_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='brand_name',
            field=models.CharField(default='Tilda', max_length=32),
        ),
        migrations.AddField(
            model_name='items',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_diary_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_gluten_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_nut_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_vegan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='rice', max_length=62),
        ),
        migrations.AddField(
            model_name='items',
            name='net_weight',
            field=models.CharField(default='1kg', max_length=5),
        ),
        migrations.AddField(
            model_name='items',
            name='position',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AddField(
            model_name='items',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='shelf_id',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(default='grain', max_length=32),
        ),
        migrations.AlterField(
            model_name='items',
            name='nutritional_info',
            field=models.TextField(blank=True),
        ),
    ]
